hillrange_ck_editor:
    default_config: normal
    configs:
        normal:
            extraPlugins: image2
            image_prefillDimensions: false
            image2_prefillDimensions: false
            image2_alignClasses:
                - align-left
                - align-right
                - center
            toolbar:
                - ['Styles','Format','FontSize']
                - '/'
                - ['Bold','Italic','Underline','StrikeThrough','-','Undo','Redo','-','PasteText','Find','Replace','-','Outdent','Indent','-','Maximize']
                - '/'
                - ['NumberedList','BulletedList','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock']
                - ['Image','Table','-','Link','TextColor','BGColor','Smiley','Source']
            uiColor: "ddcccc"
            filebrowserUploadRoute: ck_img_upload
        simple_toolbar:
            toolbar:
                - ['Bold', 'Italic', 'Strike', 'Link']
                - ['BulletedList', 'NumberedList', '-', 'Outdent', 'Indent']
                - ['Copy', 'Paste', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Source']
