hillrange_ck_editor:
    default_config: normal
    configs:
        normal:
            toolbar:
                - ['Undo','Redo','-','Source','-','PasteText','-','Maximize']
                - '/'
                - ['Styles','Format']
                - ['Bold','Italic','Underline','StrikeThrough','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock']
                - ['NumberedList','BulletedList']
                - ['Image','-','Link']
            uiColor: "ddcccc"
            filebrowserUploadRoute: ck_img_upload
            extraPlugins: image2,templates
            image2_altRequired: true
            image_prefillDimensions: false
            image2_prefillDimensions: false
            image2_alignClasses:
                - align-left
                - align-right
                - center
            height: 500px
            disableResizer: true
#    styles:
#        test:
#        - { name: "Blue Title", element: "h2", styles: { color: "Blue" }}
#            - { name: "CSS Style", element: "span", attributes: { class: "my_style" }}
#            - { name: "Widget Style", type: widget, widget: "my_widget", attributes: { class: "my_widget_style" }}

